import React, { useState } from 'react';
import { QrCode, Key, ShieldCheck, Copy, Check, Download, AlertTriangle, RefreshCw } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { Card } from '../components/common/Card';
import { Button } from '../components/common/Button';
import { Input } from '../components/common/Input';
import { Badge } from '../components/common/Badge';

export const MfaSetup: React.FC = () => {
  const { currentUser } = useAuth();
  const [totpSecret] = useState('JBSWY3DPEHPK3PXP4M2K9V8C');
  const [verificationCode, setVerificationCode] = useState('');
  const [isEnrolled, setIsEnrolled] = useState(currentUser?.totpEnabled ?? true);
  const [isVerifying, setIsVerifying] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [copiedSecret, setCopiedSecret] = useState(false);
  const [copiedCodes, setCopiedCodes] = useState(false);

  const [recoveryCodes] = useState<string[]>([
    'A9F2-48D1-C9B2',
    '3E81-99B4-7A12',
    '88C4-12E9-FA34',
    '5D20-91C7-B841',
    '9B34-66F1-2E90',
    '1A77-38C9-DF52',
    '7F81-92D0-44BA',
    'C219-58E4-77A1',
  ]);

  const handleCopySecret = () => {
    navigator.clipboard.writeText(totpSecret);
    setCopiedSecret(true);
    setTimeout(() => setCopiedSecret(false), 2000);
  };

  const handleCopyRecoveryCodes = () => {
    navigator.clipboard.writeText(recoveryCodes.join('\n'));
    setCopiedCodes(true);
    setTimeout(() => setCopiedCodes(false), 2000);
  };

  const handleDownloadRecoveryCodes = () => {
    const text = `AEGISCHAIN 2.0 EMERGENCY RECOVERY CODES\nDID: ${currentUser?.did}\nISSUED: ${new Date().toISOString()}\n\n${recoveryCodes.join('\n')}\n\nKEEP IN SECURE PHYSICAL SAFEKEEPING.`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aegischain_recovery_codes_${currentUser?.username || 'user'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    if (verificationCode.length !== 6) {
      setErrorMsg('Enter the 6 digits generated by your authenticator.');
      return;
    }

    setIsVerifying(true);
    setErrorMsg(null);

    setTimeout(() => {
      setIsVerifying(false);
      setIsEnrolled(true);
    }, 500);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="pb-4 border-b-2 border-secure-black">
        <div className="flex items-center gap-2">
          <span className="font-mono text-xs text-signal-red font-bold uppercase tracking-wider">
            AUTHENTICATION HARDENING //
          </span>
          <Badge variant={isEnrolled ? 'green' : 'amber'}>
            {isEnrolled ? 'MFA ACTIVE' : 'ENROLLMENT PENDING'}
          </Badge>
        </div>
        <h1 className="font-serif text-3xl sm:text-4xl text-bel-navy uppercase font-black tracking-tight mt-1">
          Two-Factor Authentication (TOTP)
        </h1>
        <p className="font-mono text-xs text-stone-600 mt-1">
          RFC 6238 compliant time-based one-time password configuration for <span className="font-bold text-bel-navy">{currentUser?.did}</span>
        </p>
      </div>

      {isEnrolled && (
        <div className="p-4 bg-emerald-50 border-2 border-verification-green text-stone-900 font-mono text-xs flex items-center justify-between">
          <div className="flex items-center gap-3">
            <ShieldCheck className="w-5 h-5 text-verification-green" />
            <div>
              <p className="font-bold uppercase">TOTP MFA IS ACTIVELY ENFORCED</p>
              <p className="text-stone-600">Your account requires both hardware passkey assertion and dynamic TOTP confirmation on every login.</p>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => setIsEnrolled(false)}
          >
            Reconfigure Token
          </Button>
        </div>
      )}

      {/* 3-Step Enrollment Wizard */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        {/* Step 1: QR & Secret */}
        <div className="md:col-span-6 space-y-4">
          <Card
            title="STEP 01: SCAN OR IMPORT SECRET"
            badge={<Badge variant="navy">RFC 6238</Badge>}
            theme="white"
          >
            <p className="font-mono text-xs text-stone-700 mb-4 leading-relaxed">
              Open your defence-approved authenticator (Google Authenticator, Aegis Authenticator, or YubiKey Authenticator) and scan the QR matrix:
            </p>

            {/* Generated Technical SVG QR Code Matrix */}
            <div className="p-4 bg-white border-2 border-secure-black flex flex-col items-center justify-center max-w-[240px] mx-auto shadow-ink-sm">
              <svg viewBox="0 0 120 120" className="w-44 h-44 fill-secure-black">
                {/* Simulated high-density technical QR pattern */}
                <rect x="10" y="10" width="30" height="30" fill="none" stroke="#0C2C55" strokeWidth="6" />
                <rect x="20" y="20" width="10" height="10" fill="#0C2C55" />
                <rect x="80" y="10" width="30" height="30" fill="none" stroke="#0C2C55" strokeWidth="6" />
                <rect x="90" y="20" width="10" height="10" fill="#0C2C55" />
                <rect x="10" y="80" width="30" height="30" fill="none" stroke="#0C2C55" strokeWidth="6" />
                <rect x="20" y="90" width="10" height="10" fill="#0C2C55" />
                {/* Matrix bits */}
                <rect x="45" y="15" width="6" height="6" />
                <rect x="55" y="25" width="6" height="6" />
                <rect x="65" y="15" width="6" height="6" />
                <rect x="45" y="45" width="12" height="12" />
                <rect x="65" y="45" width="6" height="6" />
                <rect x="85" y="55" width="6" height="6" />
                <rect x="55" y="65" width="12" height="12" />
                <rect x="75" y="75" width="6" height="6" />
                <rect x="95" y="85" width="6" height="6" />
                <rect x="15" y="55" width="6" height="6" />
                <rect x="25" y="65" width="6" height="6" />
                <rect x="50" y="90" width="12" height="6" />
                <rect x="70" y="95" width="6" height="12" />
                <rect x="90" y="95" width="12" height="6" />
              </svg>
              <span className="font-mono text-[10px] text-stone-500 mt-2 font-bold tracking-wider">
                TOTP · SHA1 · 30S WINDOW
              </span>
            </div>

            {/* Secret String */}
            <div className="mt-4 pt-4 border-t border-black/10">
              <label className="block font-mono text-[11px] uppercase font-bold text-stone-600 mb-1">
                Manual Entry Secret Key:
              </label>
              <div className="flex items-center gap-2">
                <code className="flex-1 font-mono text-xs bg-black/5 px-2.5 py-1.5 border border-black/20 font-bold tracking-wider select-all truncate">
                  {totpSecret}
                </code>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleCopySecret}
                >
                  {copiedSecret ? <Check className="w-3.5 h-3.5 text-verification-green" /> : <Copy className="w-3.5 h-3.5" />}
                </Button>
              </div>
            </div>
          </Card>
        </div>

        {/* Step 2: Verification Input */}
        <div className="md:col-span-6 space-y-4">
          <Card
            title="STEP 02: VERIFY AUTHENTICATOR"
            badge={<Badge variant="red">CONFIRMATION</Badge>}
            theme="white"
          >
            <form onSubmit={handleVerify} className="space-y-4">
              <p className="font-mono text-xs text-stone-700 leading-relaxed">
                Enter the active 6-digit security code currently displayed on your device to confirm synchronization:
              </p>

              <Input
                label="6-Digit Verification Code"
                placeholder="123 456"
                maxLength={6}
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value.replace(/[^0-9]/g, ''))}
                error={errorMsg || undefined}
                helperText="Code refreshes every 30 seconds"
                mono
                className="text-center tracking-widest text-lg font-bold"
              />

              <Button
                type="submit"
                variant="primary"
                size="md"
                className="w-full"
                isLoading={isVerifying}
                leftIcon={<ShieldCheck className="w-4 h-4" />}
              >
                Confirm & Bind TOTP Token
              </Button>
            </form>

            <div className="mt-4 p-3 bg-stone-100 border border-stone-300 font-mono text-[11px] text-stone-600">
              <p className="font-bold mb-1">COMPLIANCE CRITERIA:</p>
              <p>Adheres to NIST SP 800-63B guidelines for multi-factor cryptographic software tokens.</p>
            </div>
          </Card>

          {/* Step 3: Emergency Recovery Codes */}
          <Card
            title="STEP 03: EMERGENCY RECOVERY CODES"
            badge={<Badge variant="default">8 CODES</Badge>}
            theme="parchment"
          >
            <p className="font-mono text-xs text-stone-700 mb-3">
              If your authenticator device is destroyed or unavailable, use these one-time recovery codes to regain emergency access:
            </p>

            <div className="grid grid-cols-2 gap-2 font-mono text-xs bg-warm-white p-3 border border-black/20">
              {recoveryCodes.map((code, idx) => (
                <div key={idx} className="flex items-center gap-1.5">
                  <span className="text-[10px] text-stone-400">{idx + 1}.</span>
                  <code className="font-bold text-bel-navy">{code}</code>
                </div>
              ))}
            </div>

            <div className="flex items-center gap-2 mt-3">
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="flex-1"
                leftIcon={copiedCodes ? <Check className="w-3.5 h-3.5 text-verification-green" /> : <Copy className="w-3.5 h-3.5" />}
                onClick={handleCopyRecoveryCodes}
              >
                {copiedCodes ? 'Copied' : 'Copy All'}
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="flex-1"
                leftIcon={<Download className="w-3.5 h-3.5" />}
                onClick={handleDownloadRecoveryCodes}
              >
                Download (.txt)
              </Button>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};
